## Numpy Array and Basic

### Arrays
* An array is defined as a collection of items that are stored at contiguous memory location.
* It is a container which can hold a fixed amount of items and these items should be the same type.

In [2]:
import numpy as np
import time  as t

In [21]:

#1d array
arr_1d=np.array([10,20,30])
print("1D Array:",arr_1d)
#2d array
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("2D Array:\n",arr_2d)

1D Array: [10 20 30]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs NumPy Array

In [29]:
# List multipication
list_cost=[10,20,30,40,50]
print("list of sales:",list_cost*2)

Start=t.time()
list_nums=[i*2 for i in range(1000000)]
print("Time taken by list:",t.time()-Start)

# Array multipication
array_cost=np.array([10,20,30,40,50])
print("array of sales:",array_cost*2)

Start=t.time()
array_num=np.arange(100000)*2
print("Time taken by list:",t.time()-Start)

list of sales: [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
Time taken by list: 0.15341401100158691
array of sales: [ 20  40  60  80 100]
Time taken by list: 0.0004706382751464844


## NumPy Array from scratch

In [ ]:
#zeros
zeros=np.zeros((3,3))
print(zeros,"\n")

#ones
ones=np.ones((3,3))
print(ones,"\n")

#full array
full=np.full((3,3),4)
print(full,"\n")

#random
random=np.random.random((2,2))*100
print(random,"\n")

#Range
range=np.arange(10,21,0.1)
print(range)

print("Length of range:",len(range),"\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[4 4 4]
 [4 4 4]
 [4 4 4]] 

[[67.43493009 34.32869035]
 [36.27062267 97.00306063]] 

[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20.  20.1 20.2 20.3 20.4 20.5 20.6 20.7 20.8 20.9]
Length of range: 110 



## Vector,Matrix & Tensor
21/09/2026

In [5]:
#1d array
vector=np.array([1,2,3])
print("Vector:", vector)

#2d Array
Matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Matrix:\n",Matrix)

#tesor
tensor=np.array([[[10,20], [30,40]],
                 [[50,60], [70,80]]])
print("Tensor:\n",tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:
 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


## Array Properties

In [27]:
tensor=np.array([[[10,20,90], [30,40,100]],
                 [[50,60,110], [70,80,120]]])
print("Shape:",tensor.shape)
print("Dimensions:",np.ndim(tensor))
print("Size:",tensor.size)
print("Data type:",tensor.dtype)
print("length:",len(tensor))
print("Convert into diff data type:\n",tensor.astype('int32'),"\n")

Shape: (2, 2, 3)
Dimensions: 3
Size: 12
Data type: int64
length: 2
Convert into diff data type:
 [[[ 10  20  90]
  [ 30  40 100]]

 [[ 50  60 110]
  [ 70  80 120]]] 



## Array Reshape

In [42]:
# One dimensional array to two dimensional array
arr=np.arange(1,13)
reshaped_arr=arr.reshape(2,6)
print("Original array:",arr)
print("Reshaped array:\n",reshaped_arr)

arr2=np.array([[1,2,3],
               [4,5,6]])
print("Original array:\n",arr2)
reshaped_arr2=arr2.flatten()
print("Reshaped array:\n",reshaped_arr2)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Original array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [1 2 3 4 5 6]
