### - Shape of sales data
### - First three restorent data
### - Total sales per yer
### - Maximum sales per restaurant
### - Minimum sales per year 
### - Average sales per restaurant
### - Average cumulitaive sales acorss all the restaurent
### - Find Monthly avg for every restorent every year

In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

In [1]:
import numpy as np

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

years = np.array([2021, 2022, 2023, 2024])

# 1) Shape of sales data
print("Shape of sales data:", sales_data.shape)

# 2) First three restaurant data
print("\nFirst three restaurant records:\n", sales_data[:3])

# 3) Total sales per year
yearly_total = sales_data[:, 1:].sum(axis=0)
print("\nTotal sales per year:")
for yr, total in zip(years, yearly_total):
    print(f"{yr}: ₹{total:,}")

# 4) Maximum sales per restaurant
restaurant_max = sales_data[:, 1:].max(axis=1)
print("\nMaximum sales per restaurant:")
for restaurant_id, mx in zip(sales_data[:, 0], restaurant_max):
    print(f"Restaurant {restaurant_id}: ₹{mx:,}")

# 5) Minimum sales per year
yearly_min = sales_data[:, 1:].min(axis=0)
print("\nMinimum sales per year:")
for yr, min_val in zip(years, yearly_min):
    print(f"{yr}: ₹{min_val:,}")

# 6) Average sales per restaurant
avg_per_restaurant = sales_data[:, 1:].mean(axis=1)
print("\nAverage sales per restaurant:")
for restaurant_id, avg in zip(sales_data[:, 0], avg_per_restaurant):
    print(f"Restaurant {restaurant_id}: ₹{avg:,.2f}")

# 7) Average cumulative sales across all restaurants
avg_cumulative = sales_data[:, 1:].sum(axis=1).mean()
print(f"\nAverage cumulative sales across all restaurants: ₹{avg_cumulative:,.2f}")

# 8) Monthly average for every restaurant every year
print("\nMonthly average sales per restaurant per year:")
monthly_avg = sales_data[:, 1:] / 12
for restaurant_id, yearly_row in zip(sales_data[:, 0], monthly_avg):
    print(f"Restaurant {restaurant_id}:")
    for yr, monthly in zip(years, yearly_row):
        print(f"  {yr}: ₹{monthly:,.2f} per month")


Shape of sales data: (5, 5)

First three restaurant records:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

Total sales per year:
2021: ₹810,000
2022: ₹945,000
2023: ₹1,085,000
2024: ₹1,240,000

Maximum sales per restaurant:
Restaurant 1: ₹250,000
Restaurant 2: ₹190,000
Restaurant 3: ₹300,000
Restaurant 4: ₹270,000
Restaurant 5: ₹230,000

Minimum sales per year:
2021: ₹120,000
2022: ₹140,000
2023: ₹160,000
2024: ₹190,000

Average sales per restaurant:
Restaurant 1: ₹200,000.00
Restaurant 2: ₹152,500.00
Restaurant 3: ₹247,500.00
Restaurant 4: ₹225,000.00
Restaurant 5: ₹195,000.00

Average cumulative sales across all restaurants: ₹816,000.00

Monthly average sales per restaurant per year:
Restaurant 1:
  2021: ₹12,500.00 per month
  2022: ₹15,000.00 per month
  2023: ₹18,333.33 per month
  2024: ₹20,833.33 per month
Restaurant 2:
  2021: ₹10,000.00 per month
  2022: ₹11,666.67 per month
  2023: ₹13,333.33 per month
  2